spring.application.name=sistemaposjcs

server.port=8080

spring.datasource.url=jdbc:postgresql://aws-1-us-east-2.pooler.supabase.com:5432/postgres?sslmode=require
spring.datasource.username=postgres.ktlfusynkeifsgvpxbiv
spring.datasource.password=Rr#yLf@d3aRKv@L
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=always
spring.jpa.show-sql=true

spring.jackson.time-zone=America/Bogota
spring.jpa.properties.hibernate.jdbc.time_zone=America/Bogota

cloudinary.cloud-name=dxvv4sqpb
cloudinary.api-key=953786269515215
cloudinary.api-secret=RpLCUSKhTbTx6BPclSf1j0XqL78

gemini.enabled=true
gemini.model=gemini-2.5-flash
gemini.api-key=${GEMINI_API_KEY:}
