package com.sistemaposjcs.sistemaposjcs.model.Enum;

public enum TipoConsulta {

    // Ventas
    VENTAS_HOY,
    VENTAS_SEMANA,
    VENTAS_MES,
    CANTIDAD_VENTAS_HOY,
    ULTIMAS_VENTAS,
    VENTA_MAS_ALTA_DIA,
    VENTA_MAS_ALTA_MES,

    // Productos
    PRODUCTO_MAS_VENDIDO,
    TOP_PRODUCTOS_MAS_VENDIDOS,
    PRODUCTO_MENOS_VENDIDO,
    TOTAL_PRODUCTOS,
    PRODUCTOS_ACTIVOS,
    PRODUCTOS_INACTIVOS,

    // Inventario
    PRODUCTOS_STOCK_BAJO,
    PRODUCTOS_AGOTADOS,
    MOVIMIENTOS_INVENTARIO_HOY,
    PRODUCTO_MAYOR_STOCK,
    STOCK_PRODUCTO,

    // Clientes
    TOTAL_CLIENTES,
    CLIENTES_ACTIVOS,
    ULTIMOS_CLIENTES,

    // Cajas
    TOTAL_CAJAS_ABIERTAS,
    LISTAR_CAJAS_ABIERTAS,
    USUARIO_CAJA_PRINCIPAL,
    ULTIMO_CIERRE_CAJA,
    DINERO_ACTUAL_CAJA,

    // Cajeros
    CAJERO_MAS_VENTAS_MES,
    CAJERO_MAS_VENTAS_HOY,
    VENTAS_POR_CAJERO,
    RANKING_CAJEROS,

    // Métodos de pago
    INGRESOS_EFECTIVO,
    INGRESOS_TRANSFERENCIA,
    INGRESOS_NEQUI,
    METODO_PAGO_MAS_USADO,

    // Empresa
    NOMBRE_EMPRESA,
    NIT_EMPRESA,
    TELEFONO_EMPRESA,

    // General
    DESCONOCIDA
}